/*----------------------------------------------------------------------------
 * Example to include binary files into an application
 * This uVision project is part of Knowledgebase Article 3770.
 * See http://www.keil.com/support/docs/3770.htm for more details.
 *---------------------------------------------------------------------------*/

// these variables are defined in the assembler source file MyBinFile1.s and represent the data from MyBinFile1.bin 
extern const unsigned char MyBinaryImage1[];
extern const unsigned long MyBinaryImage1_length; // this constant is calculated in the assembler source file

#include "MyBinFile2.h"                           // This file is generated by the srec_cat conversion utility

unsigned int ChecksumImg1;
unsigned int ChecksumImg2;


int main (void) {
  unsigned int i;
  unsigned int checksum;

  // Calculate simple checksums of both binary images to show that the size of the images can be used
  checksum = 0;
  for (i = 0; i < MyBinaryImage1_length; i++) {  // the constant MyBinaryImage1_length is calculated in the assembler file MyBinFile1.s
    checksum += MyBinaryImage1[i];
  }
  ChecksumImg1 = checksum;

  checksum = 0;
  for (i = 0; i < MyBinaryImage2_length; i++) {  // the constant MyBinaryImage2_length is generated by the srec_cat utility
    checksum += MyBinaryImage2[i];
  }
  ChecksumImg2 = checksum;

  while(1);    // main never ends in an embedded application
}
